- name: Delete username/device from OwnTracks Recorder
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files: ../../configuration.yaml
  vars:
      store: "/var/spool/owntracks/recorder/store/"
  vars_prompt:
      - name: username
        prompt: Which user do you want to delete?
        private: no
      - name: devicename
        prompt: Which device for the user  do you want to delete?
        private: no
  tasks:

     - block:
         - name: "normalize friend - device"
           set_fact:
                userdev: "{{ item.username|lower }}-{{ item.devicename|lower }}"
                nusername: "{{ item.username }}"
                ndevicename: "{{ item.devicename }}"
           loop: "{{ friends }}"
           loop_control:
               label: "{{ item.username }}-{{ item.devicename }}"
           when: item.username|lower == username|lower and item.devicename|lower == devicename|lower

         - name: "what do we have?"
           debug: msg="{{ nusername }} - {{ ndevicename }}"

         - name: "recorder: remove {{ item }} data files file for {{ userdev }}"
           file:
              path: "{{ store }}/{{ item }}/{{ nusername|lower }}/{{ ndevicename|lower }}"
              state: absent
           loop: [ "card", "config", "last", "photos", "rec", "waypoints" ]

         - name: "recorder: delete secret for {{ userdev }}"
           shell:
              cmd: >
                 printf "{{ userdev }} DELETE" | ocat --load=keys

         - name: "recorder: clear {{ userdev }} from MQTT"
           community.general.mqtt:
              topic: "{{ item }}"
              payload: None
              username: "{{ nusername }}"
              password: "{{ lookup('file', '/usr/local/owntracks/userdata/{{ nusername }}.pass') }}"
              retain: true
              qos: "2"
              client_id: ans002
              server: "127.0.0.1"
              port: 1883
           loop:
              - "owntracks/{{ nusername }}/{{ ndevicename }}"
              - "owntracks/{{ nusername }}/{{ ndevicename }}/cmd"
              - "owntracks/{{ nusername }}/{{ ndevicename }}/info"


# TODO: remove *.pass, *.otrc?
# TODO: how to remove from configuratoin.yaml
